FROM rust:latest as chef
USER root
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
ARG SERVICE_NAME
RUN cargo build --release -p ${SERVICE_NAME}

FROM debian:bookworm-slim
ARG SERVICE_NAME
# Install OpenSSL
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/${SERVICE_NAME} ./service
CMD ["./service"]
